= RH423 Lab Scripts and Playbooks

== Usage

. Create and Switch to *Github* Directory
+
[source,bash]
----
[student@workstation ~]$ mkdir Github ; cd Github
[student@workstation Github]$
----

. Clone resources and contents
+
[source,bash]
----
[student@workstation Github]$ git clone https://github.com/tmichett/rh423_labs.git
Cloning into 'rh423_labs'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 48 (delta 11), reused 45 (delta 11), pack-reused 0
Unpacking objects: 100% (48/48), 13.63 MiB | 13.85 MiB/s, done.
----



== Playbooks

Contains playbooks to be used to setup and complete lab exercises as well as catch-up playbooks to get to specific exercises and labs.

== Scripts

Lab scripts that will call and execute the playbooks.




== Setup and Testing in RES294 Environment

.*Initial Setup*

. Configure Novello VMs
.. Load and Mount RHDS ISO to Classroom
+
[source,bash]
----
[travis@cs9 Infrastructure]$ ansible-playbook infra_classroom_repos.yml
----
+
.. Copy Materials to Classroom server and Scripts to Workstation
+
[source,bash]
----
[travis@cs9 Infrastructure]$ ansible-playbook infra_all_new_AAP2_ws_scripts.yml
----


.*Testing*

. Login to Workstation

. Run the "Setup" Script (This will need run for all new environments by students)
+
[source,bash]
----
[student@workstation ~]$ lab rh423-setup start

Preparing  for setup workstation for work:

 . Creating Github Directory...................................  SUCCESS

 . Cloning Github Repository...................................  SUCCESS

 . Copying Lab Solution Files..................................  SUCCESS

----

. Run the RHDS Install Manage Finish script (this setups up and configures the server from CH2 EoC Lab)
+
[source,bash]
----
[student@workstation ~]$ lab rhds-install-manage finish

Preparing  for lab exercise work:

 . Ensuring RHDS is Installed..................................  SUCCESS

 . Ensuring RHDS is Configured.................................  SUCCESS

----

. SSH to the *RHDS* system as "root"
+
[source,bash]
----
[student@workstation ~]$ ssh root@rhds
----

. Run the *dsconf* command to verify server is setup and configured
+
[source,bash]
----
[root@rhds ~]# dsconf slapd-rh423 backend suffix list
dc=lab,dc=example,dc=com (userroot)
----


== Classroom Deployment and Sealing Process

A new playbook has been created to supercede instructions above. The new playbook now uses the *inventory* file for local (Novello) with short hostnames and the *inventory.laptop* is meant to be run from a remote location as it sets *Ansible_Host* variables to the *WS362_** for access through the SSH tunneling setup.

.*Initial Setup*

. Run *site.yml* from local laptop with the ansible-playbook command and be sure to specify *-i inventory.laptop* to inform Ansible to use the correct inventory.
+
[source,bash]
----
travis@cs9 Infrastructure]$ ansible-playbook site.yml -i inventory.laptop
----
