#!/bin/bash
#
# Copyright 2022 Red Hat, Inc.
#
# NAME
#     lab-rh423-setup - grading script for RH318 Managing Logical Networks
#     Guided Exercise
#
# SYNOPSIS
#     lab-h423-setup {start}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start,
#     or finish for the RH423 syncing Github Content.
#
# CHANGELOG
#   * Tue Feb 1, 2022 Travis Michette <tmichett@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {
  print_header "Synchronizing ${target} content on Workstation:"
  pad " . Synchronizing Github Public Labs Repository"
  cd /home/student/Github/rh423_labs_public/
  git pull
  print_SUCCESS
  print_line

  pad " . Synchronizing Github Lab Scripts Repository"
  cd /home/student/Github/rh423_labs
  git pull
  print_SUCCESS
  print_line

  pad " . Synchronizing Lab Scripts in /usr/local/lib"
  cd /home/student/Github/rh423_labs/Playbooks/Infrastructure/
  ansible-playbook Grading_Script_Copy.yml
  print_SUCCESS
  print_line

}




############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
