#!/bin/bash
#
# Copyright 2022 Red Hat, Inc.
#
# NAME
#     lab-rh423-setup - grading script for RH318 Managing Logical Networks
#     Guided Exercise
#
# SYNOPSIS
#     lab-manage-networks {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start,
#     or finish for the RH423 Installing and Managing Red Hat Directory Server Lab.
#
# CHANGELOG
#   * Tue Feb 1, 2022 Travis Michette <tmichett@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {
  print_header "Preparing ${target} for setup workstation for work:"
  pad " . Creating Github Directory"
  mkdir /home/student/Github
  print_SUCCESS
  print_line
  pad " . Cloning Github Repository"
  cd /home/student/Github/
  git clone https://github.com/tmichett/rh423_labs_public.git
  print_SUCCESS
  print_line
}




############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
