---
- name: install RHDS 
  hosts: replica1.lab.example.com
  tasks:
    - name: install packages      
      block:

      # verify repo available

      - name: cockpit packages are installed
        dnf:
          name: 'cockpit' 
          state: present

      - name: redhat-ds:11 appstream is installed
        dnf:
          name: '@redhat-ds:11' 
          state: present

    - name: firewall ports are open
      block:

      # verify firewalld installed
      # verify firewalld started

      - name: firewalld allows 389/tcp and 636/tcp
        # RHDS install guide uses ports. could use service ldap and ldaps
        firewalld:
          port: "{{ item }}"
          permanent: true
          state: enabled
          immediate: true
        loop:
          - 389/tcp
          - 636/tcp

      - name: firewalld allows cockpit
        firewalld:
          service: "{{ item }}"
          permanent: true
          state: enabled
          immediate: true
        loop:
          - cockpit

    - name: cockpit socket enabled
      systemd:
        name: cockpit.socket
        state: started
        enabled: yes

- name: configure instance for RHDS 
  hosts: replica1.lab.example.com
  vars:
     inf_file: dscreate_notls.inf
  tasks:
    - name: copy inf file to server    
      copy: 
        src: "Files/{{ inf_file }}"
        dest: "/root/{{ inf_file }}"

    - name: use dscreate with file
      command: "dscreate from-file /root/{{ inf_file }}"
        # consider fail_when and changed_when

